#!/usr/bin/env bash

set -e

if ! command -v rustc &> /dev/null
then
    echo "Could not find Rust. Installing..."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
else
    echo "Ready to go."
fi
